{% set python_min = "3.10" %}
{% set name = "tephi" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e1cbf09c15c9c004a9f605659eeb4ec3c64bc91a7018cfde098c5413114f1e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.10
    - numpy >=1.21
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - tephi

about:
  home: https://github.com/SciTools/tephi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tephigram plotting in Python
  doc_url: https://tephi.readthedocs.io/en/stable/
  dev_url: https://github.com/SciTools/tephi

extra:
  recipe-maintainers:
    - bjlittle
    - trexfeathers
    - ESadek-MO
