{% set name = "tephi" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 382be3d954d6c62add0af5092bf3808d18860aaf263377cb0ee4cec7988c4c6c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy >=1.21
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - tephi

about:
  home: https://github.com/SciTools/tephi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tephigram plotting in Python
  doc_url: https://tephi.readthedocs.io/en/stable/
  dev_url: https://github.com/SciTools/tephi

extra:
  recipe-maintainers:
    - bjlittle
    - trexfeathers
    - ESadek-MO
