{% set python_min = '3.10' %}
{% set name = "tephi" %}
{% set version = "0.4.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55677bb5fd1e6a3850b3b404536d98a352ca7ca9d45ebb58e91b8708046b25fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.10
    - numpy >=1.21
    - scipy
    - shapely

test:
  requires:
    - python {{ python_min }}
  imports:
    - tephi

about:
  home: https://github.com/SciTools/tephi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tephigram plotting in Python
  doc_url: https://tephi.readthedocs.io/en/stable/
  dev_url: https://github.com/SciTools/tephi

extra:
  recipe-maintainers:
    - bjlittle
    - trexfeathers
    - ESadek-MO
